version = 0.1
[default.deploy.parameters]
stack_name = "floorplan-detector"
resolve_s3 = true
s3_prefix = "floorplan-detector"
region = "ca-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
