AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: FloorplanToBlender3d Application

Globals:
  Function:
    Runtime: python3.9
    Architectures:
      - x86_64
    MemorySize: 128
    Timeout: 100

Resources:
  FloorplanToBlender3dFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: python3.9
      Exclude:
        - "**/.elasticbeanstalk/**"
        - "**/.git/**"
        - "**/.github/**"
        - "**/__pycache__/**"
        - "**/*.pyc"
        - "**/*.pyo"
        - "**/*.pyd"
        - "**/.Python"
        - "**/env/**"
        - "**/pip-log.txt"
        - "**/pip-delete-this-directory.txt"
        - "**/.tox/**"
        - "**/.coverage"
        - "**/.coverage.*"
        - "**/.cache"
        - "**/nosetests.xml"
        - "**/coverage.xml"
        - "**/*.cover"
        - "**/*.log"
        - "**/.pytest_cache/**"
        - "**/.env"
        - "**/.venv"
        - "**/venv/**"
        - "**/ENV/**"
    Properties:
      Handler: app.lambda_handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  FloorplanToBlender3dApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  FloorplanToBlender3dFunction:
    Description: FloorplanToBlender3d Lambda Function ARN
    Value: !GetAtt FloorplanToBlender3dFunction.Arn 