AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: FloorplanToBlender3d Application

Resources:
  FloorplanToBlender3dFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: main.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 100
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  FloorplanToBlender3dApi:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  FloorplanToBlender3dFunction:
    Description: FloorplanToBlender3d Lambda Function ARN
    Value: !GetAtt FloorplanToBlender3dFunction.Arn 