AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: An asynchronous processing setup using DynamoDB and Lambda

Parameters:
  Stage:
    Type: String
    Description: The name of the API Gateway stage.
    Default: myStage

Globals:
  Function:
    Timeout: 120
    MemorySize: 3008
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  FloorplanDetectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Events: 
        PostEvent:
          Type: Api
          Properties:
            Path: /detect
            Method: post
            RestApiId: !Ref MyApi
    Metadata:
      Dockerfile: floorplan_detector/Dockerfile
      DockerContext: .  # Root Directory
      DockerTag: latest

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      Name: FloorplanDetectorAPI 

Outputs:
  FloorplanDetectorFunctionArn:
    Description: "ARN of the Floorplan Detector Function"
    Value: !GetAtt FloorplanDetectorFunction.Arn

  ApiURL:
    Description: "URL for our API Gateway"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}"
