AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Floorplan Detector Lambda Function

Globals:
  Function:
    Timeout: 120
    MemorySize: 3008
    Tracing: Active

Resources:
  FloorplanDetectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Timeout: 30
    Metadata:
      Dockerfile: floorplan_detector/Dockerfile
      DockerContext: .  # Root directory of the project
      DockerTag: latest

Outputs:
  FloorplanDetectorFunctionArn:
    Description: "ARN of the Floorplan Detector Function"
    Value: !GetAtt FloorplanDetectorFunction.Arn
