branch-defaults:
  main:
    environment: floorplan-recognizer-api-env
  master:
    environment: floorplan-recognizer-api-env
    group_suffix: null
environment-defaults:
  floorplan-recognizer-api-env:
    branch: null
    repository: null
global:
  application_name: floorplan-api
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.9
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
