name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    # Install the interpreter SAM needs
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        cd Recognizer_Demo/raster_api
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install aws-sam-cli
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1
        
    - name: Create necessary directories
      run: |
        cd Recognizer_Demo/raster_api
        mkdir -p .elasticbeanstalk/logs
        
    - name: Build SAM application
      run: |
        cd Recognizer_Demo/raster_api
        sam build
        
    - name: Generate deployment package
      run: |
        cd Recognizer_Demo/raster_api
        zip -r ../../deploy.zip . -x "*.git*" "*.pyc" "__pycache__/*" "*.env" "outputs/*" "uploads/*" ".elasticbeanstalk/logs/*"
        
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: floorplan-recognizer-api
        environment_name: floorplan-recognizer-api-env
        region: ca-central-1
        deployment_package: deploy.zip
        version_label: ${{ github.sha }}
        wait_for_deployment: true 