name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Python 3.9
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.9 python3.9-venv python3.9-dev
        sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.9 1
        python3.9 --version
        
    - name: Install SAM CLI
      run: |
        python3.9 -m pip install --upgrade pip
        python3.9 -m pip install aws-sam-cli
        
    - name: Install dependencies
      run: |
        python3.9 -m pip install --upgrade pip
        python3.9 -m pip install -r Recognizer_Demo/raster_api/requirements.txt
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1
        
    - name: Create necessary directories
      run: |
        mkdir -p Recognizer_Demo/raster_api/.elasticbeanstalk/logs
        touch Recognizer_Demo/raster_api/.elasticbeanstalk/logs/latest
        
    - name: SAM build
      run: |
        which python3.9
        python3.9 --version
        sam --version
        sam build --use-container
        
    - name: Generate deployment package
      run: |
        cd Recognizer_Demo/raster_api
        zip -r ../../deploy.zip . -x "*.git*" "*.pyc" "__pycache__/*" "*.env" "outputs/*" "uploads/*" ".elasticbeanstalk/logs/*"
        
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: floorplan-recognizer-api
        environment_name: floorplan-recognizer-api-env
        region: ca-central-1
        deployment_package: deploy.zip
        version_label: ${{ github.sha }}
        wait_for_deployment: true 